name: Platform request
description: Request support for a new deployment platform
labels: ['enhancement', 'platform']
body:
  - type: input
    id: platform
    attributes:
      label: Platform name
      placeholder: e.g., Fly.io
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why this platform
      description: Describe expected value and use cases.
    validations:
      required: true
  - type: textarea
    id: api
    attributes:
      label: API/docs links
      description: Include official API docs needed for integration.
